:REP
@echo START SERVER...
@set DEFAULT_DIR=D:\Study\3_COURSE\5_SEMESTR\NODE.JS\cwp-03\Default_dir
@set M_CONN=2
@echo DEFAULT_DIR = %DEFAULT_DIR%
@echo MAX_CONNECTIONS = %M_CONN%
@node server.js
@echo PRESS KEY FOR RESTART SERVER
@PAUSE
@cls
@goto REP